---
# file:roles/zookeeper/tasks/main.yml

- name: ls {{ module }}
  shell: "su -l {{ deploy_user }} -c 'cd {{ deploy_root }}/ && ls -l'"
  ignore_errors: yes

- name: init zookeeper cluster.
  script: ../files/init_zookeeper.sh
