---
# file:roles/marathon/tasks/main.yml

- name: Install jdk for {{ module }}
  shell: chdir=/opt {{ item }}
  with_items:
    - "yum install -y java-1.8.0-openjdk.x86_64"

- name: Install {{ module }}
  shell: "su -l {{ deploy_user }} -c ' [ -d {{ program_dir }}/{{ module }} ] || ( cd {{ program_dir }} && wget -N {{ download_url }}/www/mesos-cluster/{{ module }}/{{ module }}.tar.gz && tar -zxvf {{ module }}.tar.gz && rm -rf {{ module }}.tar.gz ) '"
#  ignore_errors: yes

- name: Copy start_marathon.sh to machine for {{ module }}
  template: src=start_marathon.sh.j2 dest={{ program_dir }}/{{ module }}/{{ module }}/start_marathon.sh mode=0644

- name: Copy marathon_control to machine for {{ module }}
  template: src=marathon_control.j2 dest={{ program_dir }}/{{ module }}/{{ module }}/marathon_control mode=0755
