---
# file:roles/consul/tasks/main.yml


############## install consul module
# consul
- name: copy consul to remote machine
  copy: src=consul.tar.gz dest={{ program_dir }} mode=644

- name: Install consul for consul-{{ consul_install_mode }}
  shell: chdir=/opt {{ item }}
  with_items:
    - "[ -f {{program_dir}}/consul-{{consul_install_mode}}/consul/consul ] || ( mkdir -p {{program_dir}}/{{module}}-{{consul_install_mode}} && cd {{program_dir}} && tar -zxf {{module}}.tar.gz -C ./consul-{{consul_install_mode}} && rm -rf {{module}}.tar.gz )"
  ignore_errors: yes


############## setup for server
# mesos-consul
- name: copy mesos-consul to remote machine
  copy: src=mesos-consul.tar.gz dest={{ program_dir }} mode=644
  when: consul_install_mode == "server"

- name: Install mesos-consul for consul-{{ consul_install_mode }}
  shell: chdir=/opt {{ item }}
  with_items:
    - "[ -d {{program_dir}}/mesos-consul ] || ( mkdir -p {{program_dir}}/mesos-consul && cd {{program_dir}}/ && tar -zxf mesos-consul.tar.gz && rm -rf mesos-consul.tar.gz )"
  when: consul_install_mode == "server"

- name: Setup mesos-consul control script.
  template: src=mesos-consul_control.j2 dest={{ program_dir }}/mesos-consul/mesos-consul/mesos-consul_control mode=0755
  when: consul_install_mode == "server"

- name: Setup start_mesos-consul control script.
  template: src=start_mesos-consul.sh.j2 dest={{ program_dir }}/mesos-consul/mesos-consul/start_mesos-consul.sh mode=0755
  when: consul_install_mode == "server"

############## XXX: consul agent supervisor configure file setup at roles: mesos slave mode.
############## XXX: consul agent server start at roles: mesos slave mode.
#- name: Setup supervisor conf for consul-{{ consul_install_mode }}
#  template: src=supervisord.conf.agent.j2 dest=/etc/supervisord.conf.agent mode=0644
#  when: consul_install_mode == "agent"
#
- name: Consul join for consul-{{ consul_install_mode }}
  shell: chdir=/opt {{ item }}
  with_items:
    - "{{ program_dir }}/consul-{{ consul_install_mode }}/{{ module }}/consul_control start"
    - "cd {{ program_dir }}/consul-{{ consul_install_mode }}/{{ module }} && ./consul join {{ consul_leader_ip }} "
  ignore_errors: yes
