---
# file:roles/postwork/tasks/main.yml

############## setup monit conf
# monit
- name: Setup monit conf for consul-{{ consul_install_mode }}
  template: src=monit.zk.j2 dest={{program_dir}}/monit/conf/monitrc owner={{deploy_user}} group={{deploy_user}} mode=0600
  when: cluster == "zookeeper"

# monit
- name: Setup monit conf for consul-{{ consul_install_mode }}
  template: src=monit.master.j2 dest={{program_dir}}/monit/conf/monitrc owner={{deploy_user}} group={{deploy_user}} mode=0600
  when: cluster == "mesos-master"

# monit
- name: Setup monit conf for consul-{{ consul_install_mode }}
  template: src=monit.slave.j2 dest={{program_dir}}/monit/conf/monitrc owner={{deploy_user}} group={{deploy_user}} mode=0600
  when: cluster == "mesos-slave"

####################################################################
- name: Consul join for consul-{{ consul_install_mode }}
  shell: chdir=/opt {{ item }}
  with_items:
#    - "/etc/init.d/supervisord restart"
    - "{{ program_dir }}/monit/monit_control start"
  ignore_errors: yes
