---
# file:roles/common/tasks/main.yml

############## setup for all mesos cluster host
- name: Install mesos software
  shell: chdir=/opt {{ item }}
  with_items:
    - "yum install -y mesos.x86_64 --nogpgcheck"
  ignore_errors: yes

- name: Make dir for mesos-{{ mesos_install_mode }}
  shell: chdir=/opt {{ item }}
  with_items:
    - "mkdir -p {{ program_dir }}/mesos-{{ mesos_install_mode }}"
    - "mkdir -p {{ program_dir }}/mesos-{{ mesos_install_mode }}/{data,log,store}"
  ignore_errors: yes

- name: Copy mesos_control to remote host
  template: src=mesos_control.j2 dest={{ program_dir }}/mesos-{{ mesos_install_mode }}/mesos_control owner={{deploy_user}} group={{deploy_user}} mode=0755

#- name: Copy mesos_control to remote host
#  copy: src=../files/mesos_control dest={{ program_dir }}/mesos-{{ mesos_install_mode }}/mesos_control mode=755

############## Setup supervisor conf.
- name: Setup supervisor conf for {{ module }}-{{ mesos_install_mode }}
  template: src=supervisord.conf.{{ mesos_install_mode }}.j2 dest=/etc/supervisord.conf.{{ mesos_install_mode }} mode=0644

############## Setup mesos attribute.
- name: Setup mesos attribute for {{ module }}-{{ mesos_install_mode }}
  template: src=mesos.conf.j2 dest={{ program_dir }}/mesos-{{ mesos_install_mode }}/mesos.conf owner={{deploy_user}} group={{deploy_user}} mode=0644
  when: mesos_install_mode == "slave"

####################################################################
#- name: Start server for {{module}}-{{mesos_install_mode}}
#  shell: chdir=/opt {{ item }}
#  with_items:
#    - "/etc/init.d/supervisord restart"
#    - "cd {{ program_dir }}/consul-{{ consul_install_mode }}/{{module}} && ./consul join {{ consul_leader_ip }} "
#  ignore_errors: yes
