---
# file:roles/common/tasks/main.yml

- name: make dir for opbin/opdir/work
  shell: chdir=/opt {{ item }}
  with_items:
    - mkdir -p {{ opbin_dir }}
    - mkdir -p {{ opdir_dir }}
    - mkdir -p {{ program_dir }}
  ignore_errors: yes

- name: copy falcon-agent to remote machine
  copy: src=agent.tar.gz dest={{ opbin_dir }} owner={{deploy_user}} group={{deploy_user}} mode=644

- name: install falcon-agent
  shell: "su -l {{ deploy_user }} -c ' [ -d {{ opbin_dir }}/agent ] || ( cd {{ opbin_dir }} && tar -zxvf agent.tar.gz && rm -rf agent.tar.gz ) '"
  ignore_errors: yes

- name: setup falcon transfer url
  template: src=cfg.json.j2 dest={{ opbin_dir }}/agent/cfg.json owner={{deploy_user}} group={{deploy_user}} mode=0644

- name: copy monit to remote machine
  copy: src=monit.tar.gz dest={{ program_dir }} owner={{deploy_user}} group={{deploy_user}} mode=644

- name: install monit for all hosts
  shell: chdir=/opt {{ item }}
  with_items:
    - "cd {{ program_dir }} && tar -zxvf monit.tar.gz && rm -rf monit.tar.gz"
    - "mkdir -p {{ opt_log_dir }}/monit"

#- name: install supervisor for all hosts
#  shell: chdir=/opt {{ item }}
#  with_items:
#    - "cd {{ opdir_dir }} && rm -rf supervisor && git clone https://github.com/Open-Party/supervisor.git && cd supervisor/ && bash supervisor-install.sh"
#    - "mkdir -p {{ opt_log_dir }}/supervisor"
#    - "bash {{ opbin_dir }}/agent/control restart"
